name: another_dart
description: Another World in Dart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.3.1
  collection: ^1.16.0
  csv: ^5.0.1
  vector_math: ^2.1.2
  charcode: ^1.3.1
  ffi: ^2.0.1
  sdl2: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
